### PR TITLE
Update 1-connecting.mdx

### PR DESCRIPTION
**Pull request by JoelVenable**
Documentation should mention supported feature.

https://github.com/brianc/node-postgres/issues/2513

### CODE REVIEW

**Comment by sehrope** [comment]
Replace the double spaces at sentence end with single spaces and remove the extra newlines at the top/bottom of the sample code block to match the rest of the README. 

Otherwise, looks good to me. :+1:

**Comment by charmander** [comment]
Is it possible to make this a more realistic example? It doesn’t have to be complete/runnable.

**Comment by JoelVenable** [comment]
Thanks for your feedback!  Sugggestions implemented in the update.

**Comment by charmander** [comment]
Thank you!

**Comment by sehrope** [comment]
Yes that's much nicer.

**Pull request merged**
