### PR TITLE
missing 'return' after execute the query

### PR DESCRIPTION
**Pull request by stevenchu03**
this code missing `return`
should be like in this page `https://node-postgres.com/guides/project-structure`

### CODE REVIEW

**Review by charmander — CHANGES_REQUESTED** [review]
No, that’s an expression-bodied arrow function. It’s already correct, and this change would make it a syntax error.

**Comment by stevenchu03** [comment]
> No, that’s an expression-bodied arrow function. It’s already correct, and this change would make it a syntax error.

Sorry, I didn't notice it. Thanks for clarify 🙏

**Comment by igolskyi** [comment]
> No, that’s an expression-bodied arrow function. It’s already correct, and this change would make it a syntax error.

not missing 'return'
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#function_body

**Comment by igolskyi** [comment]
> should be like in this page `https://node-postgres.com/guides/project-structure`

There is, would make also short syntax
```
module.exports = {
  query: (text, params, callback) => pool.query(text, params, callback),
}
```

**Comment by stevenchu03** [comment]
> > should be like in this page `https://node-postgres.com/guides/project-structure`
> 
> There is, would make also short syntax
> 
> ```
> module.exports = {
>   query: (text, params, callback) => pool.query(text, params, callback),
> }
> ```

Hi Igolskyi, thanks for your explanation. Last night, I learned express js with PG. and I didn't notice. I code like this:
```
module.exports = {
   query: (text, params) => {return pool.query(text,params)}
}
```

**Pull request closed without merging**
