### PR TITLE
Use gatsby-remark-autolink-headers to get improved heading ids

### PR DESCRIPTION
**Pull request by charmander**
Fixes formatted text (e.g. inline code) being rendered as “[object Object]” (#84), and multiple text children (e.g. `new Pool([config: object])`, for some reason) being rendered with commas. Also now compatible with GitHub!

Can be used to add link icons beside each heading later by removing `icon: false` from its configuration (but needs additional CSS).

### CODE REVIEW

**Comment by brianc** [comment]
Howdy - when I test the deployed page https://deploy-preview-85--hopeful-clarke-f36d36.netlify.app some of the side bar links on the right nav don't work for me anymore:

links

Any idea why some links aren't working on some of these sections for me now?

**Comment by charmander** [comment]
I never noticed that sidebar :D

Fixing, thanks!

**Comment by brianc** [comment]
Beautiful! You're amazing. Thank you! ❤️

**Comment by brianc** [comment]
also... @charmander do you want merge privileges here?  You have 'em on the main repo - makes sense to have 'em here too!

**Comment by charmander** [comment]
I already have them, but I’ll take that as a hint to merge more of the uncontroversial docs PRs :D

**Pull request merged**
